version: "3.9"
services:
  condes_server_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    # volumes:
    #   - .:/home/app
    #   - node_modules:/home/app/node_modules